#spring.application.name=bookstore-front

server:
  port: 8090

spring:
  application:
    name: bookstore-back1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka