server:
  port: 8091

spring:
  application:
    name: shoppingmall-server2  # 쇼핑몰 서버 이름

# 유레카에 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka