# 테스트 환경 전용 설정 (application-test.yml)
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: test



  application:
    name: bookstore-back1-test

  datasource:
    url: jdbc:h2:mem:bookstore-db-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 실행 시 DB 스키마 자동 업데이트
    show-sql: false  # 실행되는 SQL을 콘솔에 출력하지 않음
    properties:
      hibernate:
        format_sql: false
        show_sql: false


  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 접근 경로


logging:
    level:
      org.hibernate.SQL: OFF  # Hibernate SQL 로그 끄기
      org.hibernate.tool.hbm2ddl: OFF  # Hibernate DDL 로그 끄기
aladin:
  api:
    url: http://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey=ttbfkqlaus1419001&QueryType=ItemNewAll&MaxResults=10&start=1&SearchTarget=Book&output=js&Version=20131101
    lookup:
      url: https://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey=ttbfkqlaus1419001&QueryType=ItemNewAll&MaxResults=50&start=1&SearchTarget=Book&output=js&Version=20131101&OptResult=cover,category

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka 서버 URL (테스트 환경에서는 로컬 또는 테스트 Eureka 서버)
      fetch-registry: false  # 클라이언트가 레지스트리에서 정보를 가져오는지 여부 설정 (테스트 환경에서는 false로 설정할 수 있음)
      register-with-eureka: false  # Eureka 서버에 클라이언트를 등록할지 여부 설정 (테스트 환경에서는 false로 설정)
      enabled: false  # Eureka 클라이언트 활성화 여부 (테스트 환경에서는 false로 설정하여 Eureka와의 통신을 비활성화)
